# Generated by Django 5.2.1 on 2025-06-12 05:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gifts', '0002_gift_anonymous_contributions_gift_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Contribuinte')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Contribuinte')),
                ('phone', models.CharField(max_length=20, verbose_name='Telefone')),
                ('cpf', models.CharField(max_length=14, verbose_name='CPF')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da Contribuição')),
                ('message', models.TextField(blank=True, null=True, verbose_name='Mensagem')),
                ('payment_status', models.CharField(default='pending', max_length=50, verbose_name='Status do Pagamento')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('gift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='gifts.gift')),
            ],
        ),
    ]
