# Generated by Django 5.2.1 on 2025-06-11 14:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nome do Presente')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor do Presente')),
                ('store_name', models.CharField(blank=True, max_length=255, null=True, verbose_name='Nome da Loja')),
                ('store_type', models.CharField(blank=True, choices=[('physical', 'Física'), ('online', 'Online')], max_length=10, null=True, verbose_name='Tipo da Loja')),
                ('store_address_or_link', models.URLField(blank=True, null=True, verbose_name='Endereço da Loja ou Link do Produto')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='gift_photos/', verbose_name='Foto do Presente')),
                ('product_link', models.URLField(blank=True, null=True, verbose_name='Link do Produto')),
                ('priority', models.PositiveIntegerField(default=0, verbose_name='Prioridade')),
                ('allow_simultaneous_contributions', models.BooleanField(default=True, verbose_name='Permitir contribuições simultâneas')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gifts', to='events.event')),
            ],
        ),
    ]
