# Generated by Django 5.2.1 on 2025-06-11 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='anonymous_contributions',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gift',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='gifts/'),
        ),
    ]
