# Generated by Django 5.2.1 on 2025-06-13 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0002_gift_anonymous_contributions_gift_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='gift',
            name='fundraising_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor da Vaquinha'),
        ),
    ]
