# Generated by Django 5.2.1 on 2025-06-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gifts', '0003_gift_fundraising_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gift',
            name='product_link',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Link do Produto'),
        ),
    ]
